name: tiktok
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  image_picker: ^0.8.6+1
  video_player: ^2.6.1
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  expandable_text: ^2.3.0
  marquee: ^2.2.3
  lottie: ^2.3.2
  google_fonts: ^4.0.4
  convex_bottom_bar: ^3.2.0
  curved_navigation_bar: ^1.0.3
  google_sign_in: ^6.1.0
  font_awesome_flutter: ^10.4.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  firebase_storage: ^11.1.1 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
